const money=n=>'$'+n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ribbon(x1,y1,h1,x2,y2,h2,color,opacity=.4){const c=(x2-x1)*.48;return `<path d="M${x1},${y1} C${x1+c},${y1} ${x2-c},${y2} ${x2},${y2} L${x2},${y2+h2} C${x2-c},${y2+h2} ${x1+c},${y1+h1} ${x1},${y1+h1}Z" fill="${color}" opacity="${opacity}"/>`;}
function box(x,y,label,value,width=113){return `<rect class="label-box" x="${x}" y="${y}" width="${width}" height="48" rx="8" fill="white" fill-opacity=".94"/><text x="${x+10}" y="${y+17}" font-size="10" fill="#999da2">${escapeHtml(label)}</text><text class="chart-main" x="${x+10}" y="${y+36}" font-size="12" fill="#262b30">${money(value)}</text>`;}
function node(x,y,w,h,color,percentage){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="8" fill="${color}" stroke="white" stroke-width="2.5"/><rect x="${x+3}" y="${y+4}" width="${w-6}" height="${Math.min(31,h-8)}" rx="5" fill="white" opacity=".17"/>${h>28?`<text x="${x+w/2}" y="${y+24}" text-anchor="middle" fill="white" font-size="12">${percentage}%</text>`:''}`;}
function rawFlowChart(data, chartType){
 const expenses=data.filter(e=>e.type==='expense'),incomes=data.filter(e=>e.type==='income');const total=expenses.reduce((s,e)=>s+e.amount,0),inc=incomes.reduce((s,e)=>s+e.amount,0);
 const groups=['Food & Drinks','Entertainment','Utilities','Shopping','Subscription','Other'].map(c=>({name:c,amount:expenses.filter(e=>e.category===c).reduce((s,e)=>s+e.amount,0)}));
 if(!total&&!inc){return '<div style="height:100%;display:grid;place-items:center;color:var(--muted)">No transactions for these filters.</div>';return;}
 if(chartType==='Category breakdown'){return `<svg viewBox="0 0 860 335">${groups.map((g,i)=>`<text x="5" y="${38+i*51}" font-size="12" fill="#879099">${g.name}</text><rect x="150" y="${19+i*51}" width="${total?g.amount/total*540:0}" height="28" rx="8" fill="${['#8054ff','#3384ff','#28b8d8','#75cae1','#9cd8e5','#bddfe8'][i]}"/><text class="chart-main" x="${160+(total?g.amount/total*540:0)}" y="${38+i*51}" font-size="12">${money(g.amount)}</text>`).join('')}</svg>`;return;}
 const cardTotals=['4329','8851'].map(c=>expenses.filter(e=>e.card===c).reduce((s,e)=>s+e.amount,0));const denom=total||1;let y=36;const slots=groups.map(g=>{let h=total?g.amount/total*230:0;const slot={...g,y,h};if(h)y+=h+7;return slot;});
 let paths=ribbon(54,36,190,395,36,122,'url(#purple)',.28)+ribbon(54,36,68,395,175,64,'url(#purple)',.67)+ribbon(54,255,62,395,238,62,'#7d8daa',.44);
 let offsets=[36,175];slots.forEach(g=>{if(!g.h)return;const byCard=['4329','8851'].map(c=>expenses.filter(e=>e.category===g.name&&e.card===c).reduce((s,e)=>s+e.amount,0));let dest=g.y;byCard.forEach((v,i)=>{if(!v)return;const end=g.h*v/g.amount;const startH=v/(cardTotals[i]||1)*122;paths+=ribbon(437,offsets[i],startH,697,dest,end,i?'url(#blue)':'url(#cyan)',i?.65:.38);offsets[i]+=startH;dest+=end;});});
 return `<svg viewBox="0 0 860 335" role="img" aria-label="Money flow from income through cards to expense categories"><defs><linearGradient id="purple"><stop stop-color="#8852ff"/><stop offset="1" stop-color="#6595f8"/></linearGradient><linearGradient id="cyan"><stop stop-color="#5998ff"/><stop offset="1" stop-color="#8ddfec"/></linearGradient><linearGradient id="blue"><stop stop-color="#187aff"/><stop offset="1" stop-color="#39c3e2"/></linearGradient><pattern id="stripes" width="8" height="8" patternUnits="userSpaceOnUse" patternTransform="rotate(55)"><rect width="2" height="8" fill="#087fc8" opacity=".22"/></pattern></defs><g font-family="Arial, sans-serif"><g fill="#92999c" font-size="11"><text x="13" y="18">1. Source</text><text x="396" y="18">2. Cards</text><text x="699" y="18">3. Expenses</text></g><path d="M4 27V324M853 27V324" stroke="#dfe6e8" stroke-dasharray="5 6"/>${paths}${node(13,36,41,190,'#8050f6',inc?Math.round((incomes[0]?.amount||0)/inc*100):0)}${node(13,255,41,62,'#12161b',inc?100-Math.round((incomes[0]?.amount||0)/inc*100):0)}${node(395,36,42,122,'#3688ff',Math.round(cardTotals[0]/denom*100))}<rect x="397" y="38" width="38" height="118" rx="7" fill="url(#stripes)"/>${node(395,175,42,125,'#1776f6',Math.round(cardTotals[1]/denom*100))}${box(61,40,'Own money',incomes[0]?.amount||0)}${box(61,258,'Other income',incomes.slice(1).reduce((s,e)=>s+e.amount,0))}${box(444,180,'Card • 8851',cardTotals[1],110)}${slots.filter(g=>g.h).map(g=>`${node(697,g.y,41,g.h,'#27b9d8',Math.round(g.amount/denom*100))}<rect x="699" y="${g.y+2}" width="37" height="${Math.max(0,g.h-4)}" rx="6" fill="url(#stripes)"/>${g.h>28?box(744,g.y+1,g.name,g.amount,109):`<title>${g.name}: ${money(g.amount)}</title>`}`).join('')}</g></svg>`;
}
export function flowChart(data,chartType,t){return rawFlowChart(data,chartType).replace(/>([^<>]+)</g,(match,value)=>'>'+escapeHtml(t(value.replaceAll('&amp;','&')))+'<');}
